In [76]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score,classification_report
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [77]:
df=pd.read_csv("Zomato Dataset.csv")

In [78]:
print("shape",df.shape)
print("null values\n",df.isnull().sum())

shape (45584, 20)
null values
 ID                                0
Delivery_person_ID                0
Delivery_person_Age            1854
Delivery_person_Ratings        1908
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1731
Time_Order_picked                 0
Weather_conditions              616
Road_traffic_density            601
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             993
Festival                        228
City                           1200
Time_taken (min)                  0
dtype: int64

In [79]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45584 entries, 0 to 45583
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45584 non-null  str
 1   Delivery_person_ID           45584 non-null  str
 2   Delivery_person_Age          43730 non-null  float64
 3   Delivery_person_Ratings      43676 non-null  float64
 4   Restaurant_latitude          45584 non-null  float64
 5   Restaurant_longitude         45584 non-null  float64
 6   Delivery_location_latitude   45584 non-null  float64
 7   Delivery_location_longitude  45584 non-null  float64
 8   Order_Date                   45584 non-null  str
 9   Time_Orderd                  43853 non-null  str
 10  Time_Order_picked            45584 non-null  str
 11  Weather_conditions           44968 non-null  str
 12  Road_traffic_density         44983 non-null  str
 13  Vehicle_condition            45584 non-null  int64
 14  Type_of_order                45584 non-null  str
 15  Type_of_vehicle              45584 non-null  str
 16  multiple_deliveries          44591 non-null  float64
 17  Festival                     45356 non-null  str
 18  City                         44384 non-null  str
 19  Time_taken (min)             45584 non-null  int64
dtypes: float64(7), int64(2), str(11)
memory usage: 10.3 MB

In [80]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Delivery_person_Age,43730.0,29.566911,5.815064,15.000000,25.000000,30.000000,35.000000,50.000000
Delivery_person_Ratings,43676.0,4.633774,0.334744,1.000000,4.500000,4.700000,4.900000,6.000000
Restaurant_latitude,45584.0,17.017948,8.185674,-30.905562,12.933284,18.551440,22.728163,30.914057
Restaurant_longitude,45584.0,70.229684,22.885575,-88.366217,73.170000,75.897963,78.044095,88.433452
Delivery_location_latitude,45584.0,17.465480,7.335562,0.010000,12.988453,18.633934,22.785049,31.054057
Delivery_location_longitude,45584.0,70.844161,21.120578,0.010000,73.280000,76.002574,78.107044,88.563452
Vehicle_condition,45584.0,1.023385,0.839055,0.000000,0.000000,1.000000,2.000000,3.000000
multiple_deliveries,44591.0,0.744635,0.572510,0.000000,0.000000,1.000000,1.000000,3.000000
Time_taken (min),45584.0,26.293963,9.384298,10.000000,19.000000,26.000000,32.000000,54.000000

In [81]:
print(df.duplicated().sum())

0

In [82]:
#print(df.unique().sum()) works only with series

In [83]:
df["City"]=df["City"].replace('NaN',np.nan)
df["Festival"]=df["Festival"].replace('Nan',np.nan)

df["City"]=df["City"].fillna(df["City"].mode().iloc[0])
df["Festival"]=df["Festival"].fillna(df["Festival"].mode().iloc[0])
df.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age            1854
Delivery_person_Ratings        1908
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1731
Time_Order_picked                 0
Weather_conditions              616
Road_traffic_density            601
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             993
Festival                          0
City                              0
Time_taken (min)                  0
dtype: int64

In [84]:
numerical_cols=df[['Delivery_person_Age','Delivery_person_Ratings','Restaurant_longitude','Restaurant_longitude','Delivery_location_longitude','Vehicle_condition','multiple_deliveries','Time_taken (min)']]
numerical_cols.corr()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_longitude,Restaurant_longitude,Delivery_location_longitude,Vehicle_condition,multiple_deliveries,Time_taken (min)
Delivery_person_Age,1.000000,-0.067959,-0.009360,-0.009360,-0.000507,0.003162,0.115904,0.299523
Delivery_person_Ratings,-0.067959,1.000000,-0.014211,-0.014211,-0.013560,0.034592,-0.117631,-0.338814
Restaurant_longitude,-0.009360,-0.014211,1.000000,1.000000,0.915023,-0.038734,0.004438,0.007787
Restaurant_longitude,-0.009360,-0.014211,1.000000,1.000000,0.915023,-0.038734,0.004438,0.007787
Delivery_location_longitude,-0.000507,-0.013560,0.915023,0.915023,1.000000,-0.001946,0.004999,0.007590
Vehicle_condition,0.003162,0.034592,-0.038734,-0.038734,-0.001946,1.000000,-0.097224,-0.234456
multiple_deliveries,0.115904,-0.117631,0.004438,0.004438,0.004999,-0.097224,1.000000,0.387042
Time_taken (min),0.299523,-0.338814,0.007787,0.007787,0.007590,-0.234456,0.387042,1.000000

In [85]:
df['is_delayed'] = None
#does create a new column named is_delayed if it doesn’t already exist, and fills it with None values for all rows.

In [86]:
print(df.head(5))

       ID Delivery_person_ID  Delivery_person_Age  Delivery_person_Ratings  \
0  0xcdcd      DEHRES17DEL01                 36.0                      4.2
1  0xd987      KOCRES16DEL01                 21.0                      4.7
2  0x2784     PUNERES13DEL03                 23.0                      4.7
3  0xc8b6     LUDHRES15DEL02                 34.0                      4.3
4  0xdb64      KNPRES14DEL02                 24.0                      4.7

   Restaurant_latitude  Restaurant_longitude  Delivery_location_latitude  \
0            30.327968             78.046106                   30.397968
1            10.003064             76.307589                   10.043064
2            18.562450             73.916619                   18.652450
3            30.899584             75.809346                   30.919584
4            26.463504             80.372929                   26.593504

   Delivery_location_longitude  Order_Date Time_Orderd  ...  \
0                    78.116106  12-02-2022       21:55  ...
1                    76.347589  13-02-2022       14:55  ...
2                    74.006619  04-03-2022       17:30  ...
3                    75.829346  13-02-2022       09:20  ...
4                    80.502929  14-02-2022       19:50  ...

  Weather_conditions Road_traffic_density Vehicle_condition  Type_of_order  \
0                Fog                  Jam                 2          Snack
1             Stormy                 High                 1           Meal
2         Sandstorms               Medium                 1         Drinks
3         Sandstorms                  Low                 0         Buffet
4                Fog                  Jam                 1          Snack

  Type_of_vehicle multiple_deliveries  Festival           City  \
0      motorcycle                 3.0        No  Metropolitian
1      motorcycle                 1.0        No  Metropolitian
2         scooter                 1.0        No  Metropolitian
3      motorcycle                 0.0        No  Metropolitian
4         scooter                 1.0        No  Metropolitian

  Time_taken (min)  is_delayed
0               46        None
1               23        None
2               21        None
3               20        None
4               41        None

[5 rows x 21 columns]

In [87]:
df['is_delayed']=(df['Time_taken (min)']>=30).astype(int)
print(df.head(5))

       ID Delivery_person_ID  Delivery_person_Age  Delivery_person_Ratings  \
0  0xcdcd      DEHRES17DEL01                 36.0                      4.2
1  0xd987      KOCRES16DEL01                 21.0                      4.7
2  0x2784     PUNERES13DEL03                 23.0                      4.7
3  0xc8b6     LUDHRES15DEL02                 34.0                      4.3
4  0xdb64      KNPRES14DEL02                 24.0                      4.7

   Restaurant_latitude  Restaurant_longitude  Delivery_location_latitude  \
0            30.327968             78.046106                   30.397968
1            10.003064             76.307589                   10.043064
2            18.562450             73.916619                   18.652450
3            30.899584             75.809346                   30.919584
4            26.463504             80.372929                   26.593504

   Delivery_location_longitude  Order_Date Time_Orderd  ...  \
0                    78.116106  12-02-2022       21:55  ...
1                    76.347589  13-02-2022       14:55  ...
2                    74.006619  04-03-2022       17:30  ...
3                    75.829346  13-02-2022       09:20  ...
4                    80.502929  14-02-2022       19:50  ...

  Weather_conditions Road_traffic_density Vehicle_condition  Type_of_order  \
0                Fog                  Jam                 2          Snack
1             Stormy                 High                 1           Meal
2         Sandstorms               Medium                 1         Drinks
3         Sandstorms                  Low                 0         Buffet
4                Fog                  Jam                 1          Snack

  Type_of_vehicle multiple_deliveries  Festival           City  \
0      motorcycle                 3.0        No  Metropolitian
1      motorcycle                 1.0        No  Metropolitian
2         scooter                 1.0        No  Metropolitian
3      motorcycle                 0.0        No  Metropolitian
4         scooter                 1.0        No  Metropolitian

  Time_taken (min)  is_delayed
0               46           1
1               23           0
2               21           0
3               20           0
4               41           1

[5 rows x 21 columns]

In [88]:
feature_cols=[
    'Delivery_person_Age',
        'Delivery_person_Ratings',
        'Weather_conditions',
        'Road_traffic_density',
        'Vehicle_condition',
        'Type_of_vehicle',
        'multiple_deliveries',
        'Festival',
        'City',
        'Restaurant_latitude',
        'Restaurant_longitude',
        'Delivery_location_latitude',
        'Delivery_location_longitude',
]

In [89]:
df_clean=df[feature_cols+['is_delayed']].dropna()
print(df_clean.head(10))

    Delivery_person_Age  Delivery_person_Ratings Weather_conditions  \
0                  36.0                      4.2                Fog
1                  21.0                      4.7             Stormy
2                  23.0                      4.7         Sandstorms
3                  34.0                      4.3         Sandstorms
4                  24.0                      4.7                Fog
5                  29.0                      4.5         Sandstorms
6                  35.0                      4.0              Windy
7                  33.0                      4.2         Sandstorms
9                  21.0                      4.7              Windy
10                 25.0                      4.1         Sandstorms

   Road_traffic_density  Vehicle_condition   Type_of_vehicle  \
0                   Jam                  2        motorcycle
1                  High                  1        motorcycle
2                Medium                  1           scooter
3                   Low                  0        motorcycle
4                   Jam                  1           scooter
5                   Jam                  2  electric_scooter
6                  High                  1           scooter
7                   Jam                  2        motorcycle
9                   Jam                  0        motorcycle
10                  Jam                  0        motorcycle

    multiple_deliveries Festival           City  Restaurant_latitude  \
0                   3.0       No  Metropolitian            30.327968
1                   1.0       No  Metropolitian            10.003064
2                   1.0       No  Metropolitian            18.562450
3                   0.0       No  Metropolitian            30.899584
4                   1.0       No  Metropolitian            26.463504
5                   1.0       No  Metropolitian            19.176269
6                   1.0       No  Metropolitian            12.311072
7                   1.0       No  Metropolitian            18.592718
9                   1.0       No          Urban            22.552672
10                  2.0       No  Metropolitian            18.563934

    Restaurant_longitude  Delivery_location_latitude  \
0              78.046106                   30.397968
1              76.307589                   10.043064
2              73.916619                   18.652450
3              75.809346                   30.919584
4              80.372929                   26.593504
5              72.836721                   19.266269
6              76.654878                   12.351072
7              73.773572                   18.702718
9              88.352885                   22.582672
10             73.915367                   18.643935

    Delivery_location_longitude  is_delayed
0                     78.116106           1
1                     76.347589           0
2                     74.006619           0
3                     75.829346           0
4                     80.502929           1
5                     72.926721           0
6                     76.694878           1
7                     73.883572           1
9                     88.382885           0
10                    73.995367           1

In [90]:
df_encoded=pd.get_dummies(df_clean)
print(df_encoded.head(5))

   Delivery_person_Age  Delivery_person_Ratings  Vehicle_condition  \
0                 36.0                      4.2                  2
1                 21.0                      4.7                  1
2                 23.0                      4.7                  1
3                 34.0                      4.3                  0
4                 24.0                      4.7                  1

   multiple_deliveries  Restaurant_latitude  Restaurant_longitude  \
0                  3.0            30.327968             78.046106
1                  1.0            10.003064             76.307589
2                  1.0            18.562450             73.916619
3                  0.0            30.899584             75.809346
4                  1.0            26.463504             80.372929

   Delivery_location_latitude  Delivery_location_longitude  is_delayed  \
0                   30.397968                    78.116106           1
1                   10.043064                    76.347589           0
2                   18.652450                    74.006619           0
3                   30.919584                    75.829346           0
4                   26.593504                    80.502929           1

   Weather_conditions_Cloudy  ...  Road_traffic_density_Low  \
0                      False  ...                     False
1                      False  ...                     False
2                      False  ...                     False
3                      False  ...                      True
4                      False  ...                     False

   Road_traffic_density_Medium  Type_of_vehicle_electric_scooter  \
0                        False                             False
1                        False                             False
2                         True                             False
3                        False                             False
4                        False                             False

   Type_of_vehicle_motorcycle  Type_of_vehicle_scooter  Festival_No  \
0                        True                    False         True
1                        True                    False         True
2                       False                     True         True
3                        True                    False         True
4                       False                     True         True

   Festival_Yes  City_Metropolitian  City_Semi-Urban  City_Urban
0         False                True            False       False
1         False                True            False       False
2         False                True            False       False
3         False                True            False       False
4         False                True            False       False

[5 rows x 27 columns]

In [91]:
print(pd.get_dummies(5))

      5
0  True

In [92]:
X=df_encoded.drop('is_delayed',axis=1)
y=df_encoded['is_delayed']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [93]:
model=RandomForestClassifier(n_estimators=100,random_state=42)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

In [94]:
result_comparison=pd.DataFrame({'Actual':y_test.values,'Predicted':y_pred})

In [95]:
result_comparison['Actual Status']=result_comparison['Actual'].map({0:"Not delayed",1:"Delayed"})
result_comparison['Predicted Status']=result_comparison['Predicted'].map({0:"Not delayed",1:"Delayed"})
print(result_comparison.head(5))

   Actual  Predicted Actual Status Predicted Status
0       0          0   Not delayed      Not delayed
1       1          1       Delayed          Delayed
2       0          0   Not delayed      Not delayed
3       0          0   Not delayed      Not delayed
4       0          0   Not delayed      Not delayed

In [96]:
accuracy=accuracy_score(y_test,y_pred)*100
print("Model Accuracy:",accuracy)

Model Accuracy: 89.46196225530419